# Docker
- task: Docker@2
  inputs:
    containerRegistry: 'hub'
    repository: 'iamdkrz/microfrontends-products-list'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'hub'
        repository: 'iamdkrz/productlist'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'